qdrant:
  url: "http://localhost:6333"
  collection: "software_docs"
  limit: 7                         # Number of documents to retrieve per query
  context_limit: 5                 # Number of documents to send to the LLM context

ollama:
  host: "https://ollama.zib.de/ollama"
  model_name: "gemma3:27b"
  api_key: "MY_KEY"
  max_context_size: 2048            # Optional max context window (tokens) for LLM

embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
